services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./nginx/nginx.https.conf:/etc/nginx/templates/default.conf.template:ro
      - ./deploy/certbot/www:/var/www/certbot:ro
      - ./deploy/certbot/conf:/etc/letsencrypt:ro
